proptest-rs/proptest

- .travis.yml
- src/lib.rs
I think I might've figured out how to test with unstable enabled on travis, I couldn't figure out how to test it with travis on my fork so this PR is a work in progress for now until I see if Travis does what I expect, will reply to this again once I get it working.
> Travis test unstable

- CHANGELOG.md
- Cargo.toml
- README.md
- appveyor.yml
- readme-prologue.md
- src/arbitrary/macros.rs
- src/collection.rs
- src/lib.rs
The first step in adding automated testing for https://github.com/AltSysrq/proptest/issues/24
PR to test CI.
> Add Appveyor

- proptest-derive/Cargo.toml
- proptest-derive/src/use_tracking.rs
- proptest-derive/src/util.rs
> Bump syn => 0.15.17

- book/src/proptest/getting-started.md
- proptest/CHANGELOG.md
- proptest/Cargo.toml
- proptest/README.md
- proptest/src/arbitrary/_core/iter.rs
Fixes https://github.com/AltSysrq/proptest/issues/186.
I've already gone ahead and published 0.9.6 with this fix.
> Merge 0.9.6 into master

- proptest/src/test_runner/rng.rs
There is no reason to panic if the seed passed to a `PassThrough` RNG gets depleted. We can just return 0s instead.
> avoiding panic in passthrough RNG

- proptest/src/sugar.rs
> Prevent proptest bodies with implicit return values

- .travis.yml
- appveyor.yml
- proptest/Cargo.toml
- proptest/src/char.rs
- proptest/src/strategy/shuffle.rs
and fix broken code from api change
> Update rand to 0.8, rand_chacha to 0.3 and rand_xorshift to 0.3

- book/src/intro.md
- proptest/README.md
Use grammatically correct spelling.
> Correct spelling

- proptest/Cargo.toml
I've tagged this commit as `v1.1.0`
> Release 1.1.0

- proptest/CHANGELOG.md
Changelog : update missing release notes from 1.1, add note for updated pretty printing
closes #302
> Changelog : update missing release notes from 1.1, add note for updated pretty printing

- proptest/README.md
> Readme : add explicit link to book at the top of the readme

- book/src/proptest/tutorial/strategy-basics.md
Fixes https://github.com/proptest-rs/proptest/issues/339
if the updated link is correct, feel free to close otherwise :)
> chore(book): update strategy-basics.md

- proptest/CHANGELOG.md
- proptest/Cargo.toml
- proptest/src/string.rs
- Bump `regex-syntax` from 0.6 to 0.7
- Update `proptest/src/string.rs` for `regex-syntax` 0.7
> build(deps): bump regex-syntax from 0.6 to 0.7

- proptest/src/test_runner/failure_persistence/file.rs
> [Cleanup] FailurePersistence : update stale doc comments

- book/src/proptest/getting-started.md
> [Fix] Book : add empty main so mdbook doesn't wrap function in main

- proptest/CHANGELOG.md
the changelog for #335 got accidentally added to v1.2.0 which was released before this
> fix changelog for #335

- proptest/CHANGELOG.md
- proptest/src/test_runner/failure_persistence/file.rs
> print failed seed even if the regressions file exists

- proptest/CHANGELOG.md
- proptest/Cargo.toml
> [Release] 1.3.1 -- fix for incompatible bit-set/bit-vec versions

- .github/workflows/rust.yml
- proptest/Cargo.toml
> Build : updates MSRV to 1.65 and update CI to use rust 1.65

- proptest/src/arbitrary/_alloc/ops.rs
- proptest/src/lib.rs
Applying renames from https://github.com/rust-lang/rust/pull/116958
> fix nightly build

- proptest-derive/CHANGELOG.md
- proptest-state-machine/CHANGELOG.md
- proptest/CHANGELOG.md
- proptest/Cargo.toml
preps release of 1.4 and adds missing changelog entries
fixes #371
> [Release] 1.4.0 : adds missing changelog entries

- proptest-state-machine/src/test_runner.rs
This PR eliminates unqualified type names from the prop_state_machine macro, allowing it to be used without importing all of the required types.
This is a minor quality of life improvement, as it eliminates a class of compile errors, the cause of which is not immediately obvious from the perspective of the author of a test.
A pair of no-op unit tests are also included in a module with no imports, to verify at test compile time that the macros are hygienic.
> Fix hygiene issues with prop_state_machine macro

- proptest/src/arbitrary/_std/sync.rs
- proptest/src/strategy/mod.rs
- proptest/src/test_runner/failure_persistence/mod.rs
addresses ci failure https://github.com/proptest-rs/proptest/actions/runs/7779555907/job/21210889572
> cleanup some compiler warnings/errors

- proptest/CHANGELOG.md
- proptest/src/test_runner/runner.rs
> feat: run most recently added regression first

- book/src/proptest-derive/errors.md
> [Book] Derive : update proptest-derive to avoid talking about GATs andd just refer users to the issue tracker for Strategies of non-owned types

- proptest/src/sugar.rs
> Allow trailing comma in prop_assert_eq/ne like std

- proptest/src/test_runner/runner.rs
> Exit early if shrink disabled

- proptest/src/test_runner/config.rs
> [proptes] config: properly read environment

- .github/workflows/rust.yml
- Cargo.toml
- proptest-derive/Cargo.toml
- proptest-macro/Cargo.toml
- proptest-state-machine/Cargo.toml
- proptest/Cargo.toml
In order to enable support for this, I also bumped MSRV to 1.66
> Avoid duplicate crates

- proptest/README.md
Version number for Cargo.toml file was 1.0.0.
Change it to 1.6.0
> Update version number of proptest in instructions
