.gitignore, src/char.rs
Adds:
+ `char::CharStrategy::new_borrowed`.
Makes it a bit more ergonomic to construct a `CharStrategy` in the more usual case (not `Owned`).
=> Add CharStrategy::new_borrowed.

CHANGELOG.md, Cargo.toml, examples/dateparser_v1.rs, examples/dateparser_v2.rs, src/bits.rs, src/char.rs, src/collection.rs, src/lib.rs, src/num.rs, src/option.rs, src/result.rs, src/strategy/filter.rs, src/strategy/flatten.rs, src/strategy/map.rs, src/strategy/recursive.rs, src/strategy/statics.rs, src/strategy/traits.rs, src/strategy/unions.rs, src/string.rs, src/test_runner.rs
This PR adds:
1. Added a type alias `ValueFor<S>` where `S: Strategy`. This is a shorter way
to refer to: `<<S as Strategy>::Value as ValueTree>::Value`.
2. Added a type alias `type W<T> = (u32, T)` for a weighted strategy `T` in the
context of union strategies.
3. `TestRunner` now implements `Default`.
4. Added `Config::with_cases(number_of_cases: u32) -> Config` for simpler
construction of a `Config` that only differs by the number of test cases.
5. The default number of test cases to run is `256` (as before). This default
which is encoded by `Config::default()` is now configurable by setting the
env-var `PROPTEST_REQUIRED_CASES` to a value that can be parsed as a `u32`.
This variable is read at runtime.
6. bumped dependency `rand = "0.3.18"`.
7. Added …
=> Type aliases:  ValueFor<S> and W<T> + subsequence + other stuff

CHANGELOG.md, Cargo.toml, src/lib.rs, src/num.rs
- Added support for `i128` and `u128`. Since this is an unstable feature in
Rust, this is hidden behind the feature `unstable` which you have to
explicitly opt into in your `Cargo.toml` file.
=> Support u128 and i128 behind unstable Cargo.toml flag for nightly users.

.gitignore, CHANGELOG.md, README.md, src/lib.rs, src/strategy/map.rs, src/strategy/shuffle.rs, src/strategy/traits.rs, src/sugar.rs, src/test_runner.rs
A solution to https://github.com/AltSysrq/proptest/issues/21. [How it works](
https://github.com/AltSysrq/proptest/blob/378e430ad926e596f68f7df34d06a478b87541e5/README.md#failure-persistence)
I've taken the approach of making this "just work" by default with options to configure/disable it if desired, since I can't think of any cases where this would actually introduce breakage.
@Centril Any opinions? There's probably some stuff like filenames that might be worth bike-sheding too.
=> Add failing case persistence.

CHANGELOG.md, src/strategy/traits.rs
CHANGELOG
- `BoxedStrategy` and `SBoxedStrategy` are now newtypes instead of being type
aliases. You will only experience breaking changes if you've directly
used `.boxed()` and not `(S)BoxedStrategy<T>` but rather
`Box<Strategy<Value = Box<ValueTree<Value = T>>>>`. The probability of
breakage is very small, but still possible. The benefit of this change
is that calling `.boxed()` or `.sboxed()` twice only boxes once. This can
happen in situations where you have functions `Strategy -> BoxedStrategy` or
with code generation.
=> make (S)BoxedStrategy into newtypes

CHANGELOG.md, src/arbitrary/_std/env.rs, src/lib.rs, src/strategy/recursive.rs, src/strategy/traits.rs
+ Bugfix in `#[cfg(target_os = "windows")] fn osstring_invalid_string()`. Since this was unreleased it's not included in the CHANGELOG.
+ Some housekeeping (reorganising) + documentation fixes.
- There is a small chance of breakage if you've relied on the constraints put
on type inference by the closure in `leaf.prop_recursive(..)` having a fixed
output type. The output type is now any strategy that generates the same type
as `leaf`. This change is intended to make working with recursive types a bit
easier as you no longer have to use `.boxed()` inside the closure you pass to
`.prop_recursive(..)`.
- Reduced the heap allocation inside `Recursive` somewhat.
=> Reduce heap allocation in .prop_recursive(..) + make it more ergonomic

CHANGELOG.md, src/arbitrary/_std/thread.rs, src/strategy/flatten.rs, src/strategy/recursive.rs, src/strategy/traits.rs, src/test_runner.rs
- Some general house keeping in `test_runner.rs` and `flatten.rs`.
- Added `ArcStrategy<T>` and `.arc_boxed()` for boxed strategies affording
cheap shallow cloning by reference counting (internally using an `Arc`).
- There is a small change of breakage if you've relied on `Recursive` using
a `BoxedStrategy` as `Recursive` now internally uses `ArcStrategy<T>`
instead as well as expecting a `Fn(ArcStrategy<T>) -> R` instead of
`Fn(Arc<BoxedStrategy<T>>) -> R`.
- Reduced indirections and heap allocations inside `Recursive` somewhat.
- Removed `impl Arbitrary for LocalKeyState` since `LocalKeyState` no longer
exists in the nightly compiler.
=> ArcStrategy (and arc_boxed) + Recursive improvements + housekeeping

src/string.rs
This PR depends on #55.
Previously in #54: 
> the prior characteristic of manually overweighting certain character ranges in our generated output has been dropped
This is fixed by this PR. The prior characteristics should be retained.
=> Weigh AnyCharNoNL in old regex-syntax properly in regex-syntax 0.6 logic

src/test_runner/failure_persistence/file.rs
Split will always leave at least one part, even if there is no delimeter. This corrects the logic to use the string's length to check for emptiness before trying to split it.
(PR created with the in-browser GitHub file editor)
Fixes #63
=> Change regression file line parse

src/sugar.rs
This PR aims to allow you to write:
```rust
proptest! {
#[test]
fn addition_is_commutative(a: u8, b in 0u8..) {
...
}
}
```
and such things... The diff is a bit longer than I would have liked, but Rust won't let me define a matcher: `$p:pat : $s:ty` since `':' \in FOLLOW(pat)`.
It also fixes some documentation inaccuracies in `sugar.rs`.
=> Allow `pattern:type` in `proptest!(..)` and `prop_compose!(..)` + documentation fixes

src/lib.rs
The text refers to a range between 0 and 100, but the example was written as `0..10i32`.
=> Fix typo in tutorial

book/src/proptest/getting-started.md, proptest/README.md, proptest/examples/dateparser_v1.rs, proptest/examples/dateparser_v2.rs
I got this when trying to follow the guide:
error[E0308]: mismatched types
--> src/lib.rs:32:24
|
32 |             parse_date(s);
|                        ^
|                        |
|                        expected &str, found struct `std::string::String`
|                        help: consider borrowing here: `&s`
1 pub fn parse_date(s: &str) -> Option<(u32, u32, u32)> {$                             | 43 //-$
|
= note: expected type `&str`
found type `std::string::String`
=> Fix a type mismatch in the date parser example

proptest/src/arbitrary/mod.rs
In [1] the short description of the "arbitrary" module contains a broken
relative link to the Arbitrary trait.  In [2] the link works fine.  This
workarounds the problem by removing the link from the short description
(by pushing it down).
[1] https://altsysrq.github.io/rustdoc/proptest/0.9.0/proptest/index.html#modules
[2] https://altsysrq.github.io/rustdoc/proptest/0.9.0/proptest/arbitrary/index.html
=> Avoid a broken relative rustdoc link to Arbitrary

proptest/src/arbitrary/_std/io.rs
This helps https://github.com/rust-lang/rust/pull/65819
=> Use slice::iter

proptest/CHANGELOG.md, proptest/Cargo.toml, proptest/src/test_runner/rng.rs
The primary change is due to `rand`'s new error handling. With `rand` 0.7, the `rand::Error` type now contains either a boxed `Error` (when `std` is available) or a `NonZeroU32` (in `no_std` cases). As a result, I've introduced a new `PassThroughExhaustedError` type. When `std` is available, the implementation creates a `rand::Error` by boxing a `PassThroughExhaustedError`, while in `no_std` cases, it uses an error code representing the error.
Fixes #168.
=> Update to rand 0.7

proptest-derive/src/ast.rs, proptest/CHANGELOG.md, proptest/src/arbitrary/_alloc/alloc.rs, proptest/src/arbitrary/_alloc/collections.rs, proptest/src/arbitrary/_alloc/ops.rs, proptest/src/arbitrary/_alloc/str.rs, proptest/src/arbitrary/_alloc/sync.rs, proptest/src/arbitrary/_core/cmp.rs, proptest/src/arbitrary/_core/num.rs, proptest/src/arbitrary/_std/env.rs, proptest/src/arbitrary/_std/io.rs, proptest/src/arbitrary/_std/net.rs, proptest/src/arbitrary/_std/sync.rs, proptest/src/option.rs, proptest/src/result.rs, proptest/src/strategy/unions.rs, proptest/src/sugar.rs
LazyTupleUnion was added in #144 to improve performance of union
strategies. This commit removes the old TupleUnion impl and
replaces it with LazyTupleUnion.
=> Replace TupleUnion with LazyTupleUnion

proptest/src/arbitrary/_alloc/alloc.rs, proptest/src/test_runner/config.rs
This got broken by https://github.com/rust-lang/rust/pull/70362
Last known working was [2020-03-24](https://travis-ci.org/github/AltSysrq/proptest/jobs/669990836) and [2020-03-31](https://travis-ci.org/github/AltSysrq/proptest/jobs/672816533) was broken
=> Nightly fixes

proptest/src/test_runner/config.rs
The recent nightly compiler is generating a warning about these parenthesis.
Those warnings cause build-failures when trying to use `trybuild` to do UI tests for the `#[proptest]` macro added in PR https://github.com/AltSysrq/proptest/pull/188.
=> Fix compiler warning

book/src/proptest/no-std.md, proptest/Cargo.toml, proptest/src/test_runner/rng.rs
This allows `no_std` builds to use the `rdrand` instruction on x86
to generate a random seed for the random number generators.
An example invocation to enable it be:
```
cargo +nightly run --example fib --features alloc --features unstable --features hardware-rng --no-default-features
```
=> Add support for hardware entropy source on x86-64.

proptest/src/test_runner/rng.rs, proptest/src/test_runner/runner.rs
This change is useful for fuzzing,
as we need to know what bytes can be used with a passthrough RNG in order to create a valid corpus.
This way, we can generate a value with the Record RNG and save this as corpus for fuzzing:
```rust
let config = test_runner::Config::default();
let recorder_rng = TestRng::default_rng(RngAlgorithm::Recorder);
let mut runner = TestRunner::new_with_rng(config, recorder_rng);
let strategy = some_strategy();
let strategy_tree = match strategy.new_tree(&mut runner) {
Ok(x) => x,
Err(_) => return,
};
let data = strategy_tree.current();
let bytes_used = runner.bytes_used();
```
=> New RngAlgorithm::Recorder to record bytes used to create value

proptest-derive/src/ast.rs, proptest-derive/tests/misc.rs, proptest-derive/tests/struct.rs
This change makes it possible to implement Arbitrary for structs having more than 10 fields. I added a test in `proptest-derive/tests/misc.rs` that illustrates the problem. The struct `MoreThanTenFields` fails to compile with master today with the following error:
```
error[E0277]: the trait bound `(_IMPL_ARBITRARY_FOR_Foo::_proptest::bool::Any, _IMPL_ARBITRARY_FOR_Foo::_proptest::bool::Any, _IMPL_ARBITRARY_FOR_Foo::_proptest::bool::Any, _IMPL_ARBITRARY_FOR_Foo::_proptest::bool::Any, _IMPL_ARBITRARY_FOR_Foo::_proptest::bool::Any, _IMPL_ARBITRARY_FOR_Foo::_proptest::bool::Any, _IMPL_ARBITRARY_FOR_Foo::_proptest::bool::Any, _IMPL_ARBITRARY_FOR_Foo::_proptest::bool::Any, _IMPL_ARBITRARY_FOR_Foo::_proptest::bool::Any, _IMPL_ARBITRARY_FOR_Foo::_proptest::bool::Any, …
```
=> Support deriving Arbitrary for structs with more than 10 fields

proptest-derive/src/derive.rs, proptest-derive/tests/enum.rs
=> Fix `Arbitrary` derivation for variants with size increasing by one

book/src/proptest/getting-started.md, proptest/README.md
I'm not sure if it is a proper way to fix these links (especially the one in the readme), but now they are both not working properly.
=> Fix 'failure persistence' links

proptest/Cargo.toml, proptest/src/string.rs
This just updates `quick-error` to version 2. This did involve switching `cause` over to `source` and removing `description` since both were deprecated since rust 1.33.0 and 1.42.0 respectively. (Deja vu)
I noticed there are unrelated problems trying to test `proptest-derive` which will probably cause CI to fail.
=> Update to version 2 of quick-error

book/src/proptest-derive/getting-started.md
Updated example code in the Book to use the correct version numbers to avoid trivial errors in copy & paste.
Fixes #208
=> Fixed version number in docs

proptest/src/strategy/shuffle.rs
It must be possible for no swap to happen at each step in order to be able to generate all permutations.
Fixes #216
=> Fix shuffle algorithm

proptest/src/tuple.rs
The standard library implements `Debug` for tuples up to 12 elements, so we should be able to support them here. Occasionally we wound encounter such types in our tests.
=> Support larger tuples (up to 12 elements)

proptest/CHANGELOG.md, proptest/src/arbitrary/mod.rs, proptest/src/arbitrary/non_zero.rs
Adds `Arbitrary` impl for all the `core::num::NonZero*` types
=> `Arbitrary` impls for `NonZero*` types

CONTRIBUTING.md
"Copyright Headers" of CONTRIBUTING.md originally suggested to add your own name for copyright. However, we support both MIT and Apache licenses which allow anyone to copy and modify this source for their own use. For simplification then this change asks everyone to copyright code with the name "The proptest developers".
=> Simplifying copyright

proptest-derive/Cargo.toml, proptest-derive/src/error.rs, proptest-derive/tests/compile-fail/no-arbitrary.rs, proptest-derive/tests/compiletest.rs, proptest/CHANGELOG.md, proptest/Cargo.toml, proptest/src/arbitrary/_alloc/alloc.rs, proptest/src/arbitrary/_core/option.rs, proptest/src/lib.rs, proptest/src/num/float_samplers.rs
ci was broken on nightly this series of fixes should correct it
* dependencies.x86 was bumped to latest current version. x86 crate does not advertise an MSRV, but this was just broken on even our MSRV because the old x86 version was using a macro removed from rust, so bumping to latest seems fair.
* the calculation for the arbitrary impl of Layout was using a max_size that was too large and overflowing Layout. this has been fixed.
* test for arbitrary AllocError was referering to AllocErr which does not exist, this was fixed.
* NoneError has been removed from rust so it was subsequently removed from proptest. It was blocking compilation. evidence: https://github.com/rust-lang/rust/issues/85614
* try_reserve is stable so removed from unstable features
* try_trait has been changed to …
=> [fix-ci-nigtly] 

proptest/src/num/float_samplers.rs
The current implementation has the flaw that it doesn't sample all the floating point values in the range. For example sampling from the `f32` range [0.0, 16777216.0] will never generate any value with a fractional part even through around most of the floating point values in this range have fractional parts. 
This pull request addresses this by using a new algorithm that doesn't have that issue.
=> Improve float range sampling

book/src/proptest/tutorial/config.md, proptest/src/test_runner/config.rs
I just lost a whole bunch of time trying to figure out why setting `PROPTEST_CASES` has no effect, until I read its code and saw that this relies on the `std` feature. Would be better to document that more clearly.
=> note that PROPTEST_CASES env var requires the std feature

proptest/CHANGELOG.md, proptest/src/test_runner/config.rs
=> Config : support disabling failure persistence via env var

proptest/src/arbitrary/arrays.rs
In the previous ticket, I added `Strategy` impls for const generic arrays of strategies, but forgot about `Arbitrary` :facepalm: 
This one adds `Arbitrary` impls for const generic arrays of types which impl `Arbitrary`.
As with the previous PR, I don't think this is a breaking change.
=> Const generic arbitrary

proptest/src/sugar.rs
Closes #256
Test failures carry over from 1.0.0 tag (which this PR is based off)
=> Fix prop_assert_ne! requiring import of prop_assert!

proptest-derive/src/ast.rs, proptest-derive/tests/enum.rs, proptest-derive/tests/misc.rs, proptest-derive/tests/struct.rs, proptest/src/arbitrary/arrays.rs, proptest/src/lib.rs, proptest/src/test_runner/config.rs, proptest/src/test_runner/errors.rs, proptest/src/test_runner/runner.rs
replays/persisted failures are not counted against successful cases.
this way when `PROPTEST_CASES` <= `number of persisted cases` we will not end up never creating new cases to test against. rather, all persisted cases will be tested _and then_ a new number of cases will run equal to the number of `PROPTEST_CASES`.
addresses https://github.com/proptest-rs/proptest/issues/290
=> [replays-dont-count-cases] 

proptest/src/test_runner/errors.rs
This PR changes the `minimal failing output` to use *pretty-printed* `Debug` output instead of the default `Debug` output. The current status quo is that for complicated data structures, the output is borderline unreadable. Pretty printing using `{:#?}` alleviates this. I believe pretty-printing is the right thing to do in virtually all cases.
I also believe that this does not constitute a breaking change.
=> Use pretty printing for minimal input

.github/workflows/rust.yml
nightly needs to be cleaned before running derive tests otherwise it will fail with
```
unexpected error: '10:1: 10:30: multiple candidates for `dylib`
dependency `proptest_derive` found [E0464]'
```
and other errors
=> fix nightly derive tests

proptest/README.md
Adds a section to the readme detailing our MSRV policy.
Perhaps it's worth leaving this PR open for a while if community members want to express their opinions
=> add msrv to readme

proptest-derive/Cargo.toml, proptest-derive/src/ast.rs, proptest-derive/src/attr.rs, proptest-derive/src/error.rs, proptest-derive/src/interp.rs
I was curious why `syn` v0.15 still has so many downloads. I think this may be the main culprit :grin:
This updates all of the proc_macro related bits to v1. I'm planning on updating `syn` to v2, but figured breaking things into two PRs would make reviewing easier. The changes are largely:
- Handling `Meta::Word(_)` -> `Meta::Path(_)` since this was changed to take arbitrary paths instead of a single ident
- Fix: Ensure that the path is just a single ident
- `IntSuffix` got replaced with just returning a `&str` for the suffix
- Fix: Switch all the logic to just use the `&str`. Could also make our own version of `IntSuffix`, but wasn't sure if that would be worth it
- `Tuple` and `Tuple2` were causing a lot of headaches
- Fix: Remove them since they seem unused?
=> Update syn and friends to v1

proptest/CHANGELOG.md, proptest/Cargo.toml, proptest/src/lib.rs, proptest/src/string.rs
This removes the direct dependency on the quick-error crate, replacing the single use of `quick_error!` with (brief, straightforward) manual trait impls. quick-error remains a *transitive* dependency because it's pulled in by rusty-fork.
=> Remove quick_error dependency

proptest/CHANGELOG.md, proptest/src/arbitrary/_core/mod.rs, proptest/src/arbitrary/_core/non_zero.rs, proptest/src/arbitrary/mod.rs, proptest/src/test_runner/errors.rs
=> [Fix] NonZero : only impl Arbitrary for 128-bit NonZero nums in non-wasm targets

proptest/CHANGELOG.md, proptest/src/bits.rs, proptest/src/collection.rs, proptest/src/num.rs
There are proptest crate-only changes separated from #310 that are needed for the new proptest-state-machine crate
=> state-machine prerequisites

proptest-derive/CHANGELOG.md, proptest/CHANGELOG.md, proptest/Cargo.toml
If this is good I will tag the commit with `v1.2.0`
=> bump version to 1.2.0

proptest/src/lib.rs
This is for some reason enabled when using `alloc` instead of `std`, which prevents crates from using `proptest` on stable with only the `alloc` feature enabled.
=> Remove `#![feature(core_intrinsics)]` usage

proptest-derive/Cargo.toml
This removes a notice about future-incompatible code from criterion 0.2.
=> deps: Update criterion to v0.5

proptest/src/sample.rs
This is useful for generic code, as the comment says. As a workaround
I've had to define a newtype wrapper around `Index` to achieve the same
goal, so it would be lovely to have this be upstream! 😄
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/altsysrq/proptest/134)
=> add AsRef<Index> impl for Index

proptest-derive/Cargo.toml, proptest-state-machine/Cargo.toml, proptest/Cargo.toml, proptest/test-persistence-location/single-crate/Cargo.toml, proptest/test-persistence-location/workspace/member/Cargo.toml
The new recommendation is to follow the SPDX 2.1 standard. This allows automatic license verification software to work properly. Reference: https://doc.rust-lang.org/cargo/reference/manifest.html#the-license-and-license-file-fields
=> Update license field following SPDX 2.1 license expression standard

proptest/CHANGELOG.md, proptest/Cargo.toml, proptest/src/bits.rs
I noticed that `VarBitSet::saturated` takes a significant amount of time when generating data with `VecStrategy`. There are two perf issues:
1. not making use of the size hint in `FromIterator` leads to repeated grow calls
2. saturated should use `from_elem` since we're setting all bits
=> Make VarBitSet saturated + FromIterator efficient

proptest-derive/src/ast.rs, proptest-derive/src/tests.rs
This is a new lint added in Rust 1.72. See comment for why.
=> [proptest-derive] disable clippy::arc_with_non_send_sync

proptest/src/sugar.rs
Often, the strategies passed into `prop_oneof!` are `BoxedStrategy` instances, which are not Send or Sync. Rust 1.72 has a new `arc_with_non_send_sync` clippy lint that fires in these cases.
The double-curly-braces are not strictly required, but allow the expression to be annotated with an attribute.
=> [proptest] silence clippy::arc_with_non_send_sync warning with prop_oneof

proptest/Cargo.toml, proptest/src/test_runner/rng.rs
The Rust standard library includes some byteorder-like helper functions for a while already. This commit replaces the use of byteorder with these helper functions.
----
I have no particular reason for this except for trying to remove a dependency. `byteorder` is not a "bad" dependency, but it still seemed unnecessary to me to do what is being done here.
Feel free to tell me that this is not worth it. :-)
=> Remove byteorder dependency

proptest-state-machine/CHANGELOG.md, proptest-state-machine/Cargo.toml, proptest-state-machine/src/test_runner.rs
Before the feature was finalized, the state machine support was included in the core proptest crate that uses "std" feature. After crate split, the "std" feature was missing in the new crate so the code was dead.
The "std" feature is added to proptest-state-machine as a default feature allowing to switch the logging off in non-std env.
=> state-machine: fix logging by adding "std" feature

proptest/src/arbitrary/_std/path.rs, proptest/src/lib.rs, proptest/src/path.rs, proptest/src/string.rs
Followup to #362. Includes documentation. I'm pretty new to this and I had to cargo-cult a bit so please point out issues!
Thanks to Michael for starting work on this!
=> Add PathBuf Arbitrary impl with tests

proptest/src/sugar.rs
clippy::ignored_unit_patterns is a new lint rule that the generated code seems to be violating. This fixes it so the generated code passes lint checks that the end user wants.
=> Follow new lint rule in macro generation

proptest-state-machine/src/test_runner.rs
When `#![proptest_config(..)]` is not provided, the macro should use the default proptest config. This PR fixes an issue that prevents this from working -- there's a reference to `config` that should be `Default::default()` instead:
```
error[E0425]: cannot find value `config` in this scope
|
2132 | /     prop_state_machine! {
2133 | |         #[test]
2134 | |         fn run(sequential 1..20 => MyTest);
2135 | |     }
| |_____^ not found in this scope
|
= note: this error originates in the macro `prop_state_machine` (in Nightly builds, run with -Z macro-backtrace for more info)
```
=> Fix prop_state_machine cannot find value `config`

proptest-derive/tests/compile-fail/must-be-debug.rs, proptest/src/arbitrary/_alloc/ops.rs, proptest/src/lib.rs
=> fix compile fail test: must be debug

proptest-state-machine/CHANGELOG.md, proptest-state-machine/src/strategy.rs
- fixes #387 (tbc)
- based on https://github.com/proptest-rs/proptest/pull/389 that fixes ci
=> state-machine: don't limit number of transitions that can be deleted in shrinking

.github/workflows/rust.yml, proptest-derive/Cargo.toml, proptest-derive/src/ast.rs, proptest-derive/src/tests.rs
For enums with a lot of variants the `Strategy` synthesized by the `#[derive(Arbitrary)]` macro is a right-deep `TupleUnion`.
This commit adds a `boxed_union` feature, which when enabled will change the `enum` expansion to use `Union<BoxedStrategy<Self>>`.
see github issues:
https://github.com/proptest-rs/proptest/issues/249 https://github.com/proptest-rs/proptest/issues/152
code included from https://github.com/proptest-rs/proptest/issues/249#issuecomment-1367820389
=> add boxed union feature to circumvent stack overflow

proptest-state-machine/CHANGELOG.md, proptest-state-machine/proptest-regressions/strategy.txt, proptest-state-machine/src/strategy.rs
This PR fixes an issue where, after the initial state in a state machine test has been simplified, it will not be re-complicated when this results in a successful run. As a result, when this situation is encountered, the test will report a "minimal failing input" that is actually a successful input - the input that is just barely simpler than the minimal failing input.
I've also added a proptest that detects the failure, along with two regression seeds, for good measure.
=> Fix re-complication of initial state

proptest/CHANGELOG.md, proptest/src/test_runner/config.rs
=> [Fix] Config : don't clobber existing failure-persistence config during contextualization

proptest-derive/src/ast.rs, proptest-derive/src/tests.rs
On latest nightly, with the introduction of https://github.com/rust-lang/rust/issues/120363, proptest derives don't pass lints anymore, e.g.
```console
error: non-local `impl` definition, they should be avoided as they go against expectation
--> crates/primitives/src/account.rs:15:12
|
15 | pub struct Account {
|            ^^^^^^^
|
= help: move this `impl` block outside the of the current constant `_IMPL_ARBITRARY_FOR_Account`
= note: an `impl` definition is non-local if it is nested inside an item and neither the type nor the trait are at the same nesting level as the `impl` block
= note: one exception to the rule are anon-const (`const _: () = { ... }`) at top-level module and anon-const at the same nesting as the trait or type
= note: this lint may become deny-by-default in the …
```
=> fix: use anon-const for wrapping expanded impls

proptest/src/arbitrary/_alloc/collections.rs, proptest/src/arbitrary/_core/cell.rs, proptest/src/bits.rs, proptest/src/lib.rs, proptest/src/option.rs, proptest/src/result.rs
https://blog.rust-lang.org/2024/02/28/Clippy-deprecating-feature-cargo-clippy.html
=> Fix feature = "cargo-clippy" deprecation

proptest/src/array.rs
`core::array::from_fn` is stable since 1.63, and the current MSRV is 1.64.
Ideally `unarray` would get entirely replaced but `core::array::try_from_fn` is
still unstable.
=> Use `array::from_fn` instead of `unarray::build_array`

proptest-state-machine/CHANGELOG.md, proptest-state-machine/src/strategy.rs, proptest-state-machine/src/test_runner.rs
This PR adds a new shrinking step to `proptest_state_machine::SequentialValueTree` that deletes all transitions not seen by the test runner as the first step. This is related to #387.
To do that it changes the value type from a `Vec<Transition>` to a new wrapper type `ObservedVec<T>`. This new type contains a counter that is shared with `SequentialValueTree` and keeps track of how many transitions have been seen by the test runner.
The shared counter is reset on each call to `simplify` / `complicate`, therefore it is no longer valid to call `current` multiple times without calling `simplify` and/or `complicate` in between.
Given my (admittedly limited) understanding of how `proptest` works this is not an issue as the intention is for the value tree to be used in a loop where each …
=> Delete unseen transitions in state machine test

book/src/proptest/tutorial/enums.md, book/src/proptest/tutorial/test-runner.md
[TestRunner doc page](https://proptest-rs.github.io/proptest/proptest/tutorial/test-runner.html) and [Enums doc page](https://proptest-rs.github.io/proptest/proptest/tutorial/enums.html) have broken links to `TestRunner` and `prop_oneof!` respectively. Fixing these to point to correct doc.rs link
=> doc: fix broken links in book

proptest/CHANGELOG.md, proptest/src/arbitrary/traits.rs
=> [Doc] Arbitrary : add a note about the derive macro in Arbitrary's documentation

proptest/CHANGELOG.md, proptest/src/num.rs
Currently, if an empty range is used as base for a strategy, the generation will fail during the call to the `rand` crate as it cannot sample from an empty range. This PR creates a panic during the tree construction (the soonest we can) with a descriptive message, facilitating tracking the source of the issue.
Solves https://github.com/proptest-rs/proptest/issues/449
The panic message test pattern follows Rust's core library https://github.com/rust-lang/rust/blob/a1bad57fa59a8069a6ebb05cd6a2ae73c88b2e98/src/test/run-pass/panic-uninitialized-zeroed.rs
=> Detect empty ranges during tree creation

proptest-state-machine/CHANGELOG.md, proptest-state-machine/src/strategy.rs, proptest/src/test_runner/runner.rs
When shrinking a state machine test, proptest either shrinks a transition, deletes a transition or attempts to shrink the initial state. The `check_acceptable` function however uses the `last_valid_initial_state` which isn't the correct one if we just shrank / complicated the initial state.
=> fix: check preconditions on correct state

proptest/src/strategy/unions.rs
Fix a typo in the rustdoc for the proptest::strategy::Union struct.
=> docs: Stragegy -> Strategy in rustdoc for Union

proptest/Cargo.toml
Given that no code changes were needed, I could change the version requirement to `>=0.5.2, <=0.8`. This allows a range of versions of the dependency. 
I could provide CI jobs to verify that the minimal specified requirement keeps working. 
Please let me know if you want me to do either of these.
=> build(deps): Update `bit-set` and `bit-vec` to 0.8.0

proptest-state-machine/src/strategy.rs
The `Sequential` struct is where most of the useful functionality of `proptest-state-machine` lives. Currently, it can only be constructed via the `ReferenceStateMachine` trait.
By introducing a dedicated ctor function, users are not bound to use the `ReferenceStateMachine` trait but can initialise the test to their liking whilst still being able to use all of the shrinking functionality built into `Sequential`.
Replaces: #493.
=> feat: introduce `Sequential::new`

book/src/proptest-derive/errors.md, proptest/src/test_runner/config.rs
=> 234 config with failure persistence

proptest-derive/src/use_tracking.rs, proptest-derive/tests/use_tracker.rs
The implementation of UseTracker expects that iteration over items of used_map gives items in insertion order. However, the order of BTreeSet is based on Ord, not insertion.
I use a Vec of tuples. An alternative would be indexmap crate, but since the maps are supposed to be very small, it is probably not worthy. There already was a mention about the crate in the comments worrying about compile times.
replaces #260
=> Fix bounds generation for generics in derive(Arbitrary)

proptest/Cargo.toml
=> Make libm optional in a std environment

book/src/proptest/tutorial/arbitrary.md
=> [book] document example of manual arbitrary impl

.github/workflows/rust.yml, book/src/proptest/no-std.md, prerelease-checks.sh, proptest/Cargo.toml, proptest/gen-docs.sh
commit 69c25f00aed0e58f6cd8b9a141ab2861f889dc72 made it so libm no longer included in std features and is moved to an explicit no_std feature, however this broke the build and is confusing for no_std docs. no_std docs force using "alloc", relatedly everywhere we use "alloc" we should also use "no_std".
=> add no_std to alloc contexts

proptest-derive/src/ast.rs, proptest-derive/src/tests.rs
Simplest possible fix for https://github.com/proptest-rs/proptest/issues/447
=> Fix non-local impl nightly warning with `allow(non_local_definitions)`

book/src/proptest/wasm.md, proptest/src/arbitrary/primitives.rs, proptest/src/num.rs, proptest/src/test_runner/config.rs, proptest/src/test_runner/runner.rs
=> 458 fix wasm

proptest/CHANGELOG.md, proptest/Cargo.toml, proptest/src/test_runner/mod.rs, proptest/src/test_runner/runner.rs, proptest/src/test_runner/scoped_panic_hook.rs
When `handle-panics` is enabled, panic backtrace which happens in test case is silenced instead of spitting it to console
This PR is part of #421/#517 which doesn't change public API. Part with backtraces capture will be presented as separate PR
P.S: Do we actually need feature to gate this out? Or should it be just enabled by `std`?
=> Add feature `handle-panics`

proptest/src/test_runner/scoped_panic_hook.rs
follow-up for #525 to fix no-std build (see e.g. https://github.com/proptest-rs/proptest/actions/runs/12227857268/job/34105201245)
=> fix no-std build

proptest-derive/src/ast.rs
Hiya! Big fan of `proptest`, it's been fantastic for testing my code, and the commit-friendly regressions file is such a lovely touch.
This is tiny little change to `proptest-derive` that helps things work when `proptest` is not a **direct** dependency, such as when it has been re-exported from another crate.
As far as I'm aware, this is a safe change that shouldn't break anything for anyone currently using it, but if I'm wrong about that, please let me know.
If there's any changes you'd like me to make, I'd be glad to do so.
Thanks again, crates like this are valuable parts of the testing ecosystem. ❤️
=> adds support for re-exporting crate

proptest-derive/CHANGELOG.md, proptest-derive/Cargo.toml, proptest-derive/src/tests.rs, proptest-derive/tests/compiletest.rs
proptest-derive: prepare 0.5.1 patch release
=> proptest-derive: prepare 0.5.1 patch release

proptest-derive/CHANGELOG.md, proptest/CHANGELOG.md, proptest/Cargo.toml
prep v1.6.0 release
also fix markdown on release notes
=> prep v1.6.0 release

.github/workflows/rust.yml, proptest-macro/src/lib.rs, proptest-macro/src/property_test/codegen/arbitrary.rs, proptest-macro/src/property_test/codegen/mod.rs, proptest-macro/src/property_test/codegen/snapshots/proptest_macro__property_test__codegen__tests__generates_arbitrary_impl.snap, proptest-macro/src/property_test/codegen/test_body.rs, proptest-macro/src/property_test/mod.rs, proptest-macro/src/property_test/tests/mod.rs, proptest-macro/src/property_test/tests/snapshot_tests.rs, proptest-macro/src/property_test/tests/snapshots/proptest_macro__property_test__tests__snapshot_tests__custom_strategy.snap, proptest-macro/src/property_test/tests/snapshots/proptest_macro__property_test__tests__snapshot_tests__mix_custom_and_default_strategies.snap, proptest-macro/src/property_test/utils.rs, proptest-macro/src/property_test/validate.rs, proptest/Cargo.toml
=> [proptest-macro] add the ability to specify custom strategies

proptest/src/test_runner/config.rs, proptest/src/test_runner/rng.rs, proptest/src/test_runner/runner.rs
closes #548 
Ideally I wouldn't have to define the `RngSeed` type and could have just used an optional. However, the fact that `parse_or_warn` takes a `&mut T` and not a `&mut Option<T>` made it difficult to keep common parsing logic. Maybe you have another suggestion?
=> Add PROPTEST_RNG_SEED to take initial TestRunner seed from environment

proptest/src/sample.rs
This will already fail further down the call-chain but asserting it here gives much better stracktraces, allowing users to debug much faster, where in their potentially very large and composed strategy the problem is.
=> chore: assert collection in `sample::select` is not empty

proptest-derive/CHANGELOG.md, proptest-derive/src/error.rs
This PR fixes the error messages emitted by proptest-derive. Before, the URLs had the following format:
> https://PATH/TO/foo#E0001
Not only the URL doesn’t exist, but also the fragment is in uppercase characters (E0123) instead of the lowercase string (e0123) that rustdoc generates.
Now, they use the correct format instead:
> https://proptest-rs.github.io/proptest/proptest-derive/errors.html#e0001
I added a unit test to check the output format of `mk_err_msg`. Sadly it’s not possible to test the URL format in the compile-fail tests because it looks like the support from [compiletest-rs](https://github.com/Manishearth/compiletest-rs) for multi-line error messages is broken.
=> Fix URLs in proptest-derive error messages

proptest/src/sugar.rs
i.e. `prop_assert!(false,)` should be valid in an analogous way to `prop_assert_eq!(1, 2,)` being valid.
=> Allow prop_assert! with trailing comma

CONTRIBUTING.md
Description:
This pull request corrects a typo in the CONTRIBUTING.md file, changing "Abitrary" to the correct spelling "Arbitrary" for improved clarity and professionalism.
=> Fix typo in CONTRIBUTING.md: "Abitrary" → "Arbitrary"

proptest/src/arbitrary/_alloc/alloc.rs
based on: https://salsa.debian.org/rust-team/debcargo-conf/-/blob/master/src/proptest/debian/patches/fix-arithmetic-overflow.patch?ref_type=heads
=> fix for 32 bit processors

proptest/src/sugar.rs
If `format!` was not defined for a user of the `prop_assume` macro (e.g. with `no_std`), you'd get a compilation error. This PR makes it so that all macros accessible to the user use fully qualified paths everywhere.
Closes #557
=> Fix macro hygiene in user-facing macros.

.github/workflows/rust.yml, proptest-macro/src/property_test/codegen/test_body.rs, proptest-macro/src/property_test/utils.rs, proptest/tests/attr_macro.rs
Closes #601
Also adds a small regression test, which should also be a good place to put
more rigorous testing for the attr macro.
=> fix attr-macro eating mutability modifiers
